spring.application.name=DANMONHOCJ22E

# datasource for SQL Server
# using host and explicit port avoids browser/UDP resolution issues
spring.datasource.url=jdbc:sqlserver://LENXOX1:1433;databaseName=WEBQLDPKS;encrypt=false
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
