spring.application.name=DANMONHOCJ22E

spring.datasource.url=jdbc:sqlserver://localhost;databaseName=WEBQLDPKS;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

# JPA / Hibernate settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# H2 console for quick local inspection
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
